# **Python code**

In [2]:
import pandas as pd

df = pd.read_csv("/sales.csv.txt")

df

         Date   Product  Quantity  Price
0  2026-01-01    Laptop         2  45000
1  2026-01-02     Mouse        10    500
2  2026-01-03  Keyboard         5   1200
3  2026-01-04   Monitor         3  12000
4  2026-01-05     Mouse         8    500
5  2026-01-06    Laptop         1  45000
6  2026-01-07  Keyboard         7   1200
7  2026-01-08   Monitor         2  12000
8  2026-01-09     Mouse        12    500
9  2026-01-10    Laptop         3  45000

# **Data Basic Information**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      10 non-null     object
 1   Product   10 non-null     object
 2   Quantity  10 non-null     int64
 3   Price     10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

# **Revenue**

In [4]:
df["Revenue"] = df["Quantity"] * df["Price"]

df

         Date   Product  Quantity  Price  Revenue
0  2026-01-01    Laptop         2  45000    90000
1  2026-01-02     Mouse        10    500     5000
2  2026-01-03  Keyboard         5   1200     6000
3  2026-01-04   Monitor         3  12000    36000
4  2026-01-05     Mouse         8    500     4000
5  2026-01-06    Laptop         1  45000    45000
6  2026-01-07  Keyboard         7   1200     8400
7  2026-01-08   Monitor         2  12000    24000
8  2026-01-09     Mouse        12    500     6000
9  2026-01-10    Laptop         3  45000   135000

# **Total Revenue**

In [5]:
total_revenue = df["Revenue"].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 359400

# **Product-Wise Analysis**

In [6]:
product_summary = df.groupby("Product").agg(
    Total_Quantity=("Quantity", "sum"),
    Total_Revenue=("Revenue", "sum")
).reset_index()

product_summary

    Product  Total_Quantity  Total_Revenue
0  Keyboard              12          14400
1    Laptop               6         270000
2   Monitor               5          60000
3     Mouse              30          15000

# **Top-Selling Product**

In [8]:
top_product = product_summary.loc[
    product_summary["Total_Quantity"].idxmax()
]

print("Top-selling product:", top_product["Product"])
print("Units sold:", top_product["Total_Quantity"])

Top-selling product: Mouse
Units sold: 30

# **Highest Revenue Product**

In [9]:
highest_revenue_product = product_summary.loc[
    product_summary["Total_Revenue"].idxmax()
]

print("Highest revenue product:", highest_revenue_product["Product"])
print("Revenue:", highest_revenue_product["Total_Revenue"])

Highest revenue product: Laptop
Revenue: 270000

# **Summary**

In [10]:
print("===== SALES DATA ANALYSIS =====")
print("Total Revenue: ₹", total_revenue)
print("Top-selling Product:", top_product["Product"])
print("Units Sold:", top_product["Total_Quantity"])
print("Highest Revenue Product:", highest_revenue_product["Product"])
print("Highest Product Revenue: ₹", highest_revenue_product["Total_Revenue"])

===== SALES DATA ANALYSIS =====
Total Revenue: ₹ 359400
Top-selling Product: Mouse
Units Sold: 30
Highest Revenue Product: Laptop
Highest Product Revenue: ₹ 270000